### PR TITLE
changing loadtxt to use comments as # not as skiprows

### PR DESCRIPTION
**Pull request by lili-alderson**
light curve fitting previously loaded in lc and wavelength txt files uses skiprows to avoid headers - this required the user's files to have the exact right number of lines as a header or data would also be skipped. np.loadtxt now uses comments="#" to make this robust for all python headers no matter the number of lines

### CODE REVIEW

**Comment by hrwakeford** [comment]
I ran ExoTiC-ISM from develop to get a comparison file, and then tried to run it with this change and it cannot read in the test files properly, with the following error:
```
WORKING ON EXOPLANET W17

Traceback (most recent call last):
  File "marginalisation.py", line 738, in <module>
    x, y, err, sh = np.loadtxt(os.path.join(dataDir, get_timeseries), comments="#", unpack=True)
  File "/Users/iz19726/miniconda3/envs/exoticism/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1159, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/Users/iz19726/miniconda3/envs/exoticism/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1087, in read_data
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/Users/iz19726/miniconda3/envs/exoticism/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1087, in <listcomp>
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/Users/iz19726/miniconda3/envs/exoticism/lib/python3.7/site-packages/numpy/lib/npyio.py", line 794, in floatconv
    return float(x)
ValueError: could not convert string to float: 'WASP-17b'
```

**Comment by hrwakeford** [comment]
This appears to be because the test files do not have comments using `#` this will need to be updated in the files and documented clearly in a commit

**Comment by hrwakeford** [comment]
Could you also please add in a comment in the file stating the need for comment lines in the data files using `#`

**Comment by lili-alderson** [comment]
> Could you also please add in a comment in the file stating the need for comment lines in the data files using `#`

This will work best in the README.md, I will leave it to you to decide on how best to fold in new wording

**Comment by hrwakeford** [comment]
detail has been added to the readme file to state that headers should start with `#`

**Review by hrwakeford — APPROVED** [review]
All checks passed and the code now works with the headers posted with `#` instead of fixed skiprows.

This makes it better and more open source friendly.

**Pull request merged**
