### PR TITLE
Fix plots in PDF report

### PR DESCRIPTION
**Pull request by ivalaginja**
Working on issue #53, improving the plots in the PDF report.

### CODE REVIEW

**Comment by ivalaginja** [comment]
I confirmed that the masked arrays get plotted correctly, although I noticed that I needed to use circle markers to make sure every non-masked data point actually shows up in the plots.

The two figures currently look like this (this is W17 data):
weights-stdr-rl

residuals_best-model

Some questions for @hrwakeford:
- [ ] Do we want the masked data points to appear too, but e.g. in a different color or with a different marker (or both)?
- [ ] Could you check all the labels and units and let me know if there is something we need to change?

**Comment by hrwakeford** [comment]
1) Yes it would be good to plot the missing points in grey with an alpha of 0.7 (or similar). 
2) The labels on the Marginalization plot look good. The labels of the light curve plot need to be more specific. The top: "Raw lightcurve". 
Middle: "best-fit model" and "Corrected lightcurve" 
Both top and middle are Y-axis = normalised flux. 
Bottom: "standard deviation bound" the points do not need to be labeled as the Y-axis will tell them what it is the Y-axis = Residuals (ppm)

**Comment by hrwakeford** [comment]
The first caption should be: 
Top: Evidence-based weight associated with each systematic model when fit with the data. Middle: Standard deviation of the residuals after correcting for each systematic model. Bottom: Radius ratio measured from the transit depth when the light curve has been corrected using each systematic model.

The second caption:
Top: Input lightcurve with no systematic model correction applied. Middle: Lightcurve corrected by highest weight systematic model plotted with the smooth planetary transit model centred on the mid-transit time. Bottom: Residuals and uncertainties associated with the middle panel lightcurve. The upper and lower standard deviation bounds are shown in dotted lines relative to zero.

**Comment by ivalaginja** [comment]
Captions and labels adjusted, see below.
I also added plot points for he masked values and sent separately to @hrwakeford for review.

Screen Shot 2019-12-30 at 22 13 44

Screen Shot 2019-12-30 at 22 13 58

**Pull request merged**
