### PR TITLE
Webb ld1

### PR DESCRIPTION
**Pull request by hrwakeford**
Added in files to compute the limb darkening for JWST NIRSpec Prism and G395H instruments

### CODE REVIEW

**Review by lili-alderson — CHANGES_REQUESTED** [review]
You should update the documentation for `limb_dark_fit()` in `limb_darkening.py` to reflect the fact that some JWST instruments are now supported. 

I also wonder whether the variable names in lines 285-292 in `limb_darkening.py` should be updated to reflect the fact that this code is not only for HST now (e.g., you currently define `wsHST = wssens` for both HST and JWST cases. I don't know that this is a 100% necessary change, but it could prevent confusion later down the line

**Comment by hrwakeford** [comment]
Great thanks I will get on those changes tomorrow.

**Comment by hrwakeford** [comment]
@lili-alderson I have made the suggested changes to the limb_darkening.py file

**Review by lili-alderson — APPROVED** [review]
No further changes necessary, approved.

**Pull request merged**
